name: Deploy Portfolio to IONOS
on:
  push:
    branches:
      - main # Change en "master" si besoin

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        sftp_only: true
        local_path: './*' # Prend tous les fichiers à la racine du repo
        remote_path: '/'  # sous-dossier sur IONOS
