name: Deploy Portfolio to IONOS
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: ⚙️ Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Version standard et stable de Node

    - name: 📦 Install dependencies
      run: npm install

    - name: 🛠️ Build project
      run: npm run build

    - name: 📂 Sync files via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        sftp_only: true
        local_path: './dist/*' # Seulement le dossier compilé
        remote_path: '/'
